# Generated by Django 2.1.11 on 2020-02-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pfm', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTambah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_publish', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_publish', models.BooleanField()),
            ],
            options={
                'db_table': 'app_pfm_article',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(),
        ),
        migrations.AlterModelTable(
            name='article',
            table='app_pfm_article',
        ),
    ]
