# Generated by Django 2.1.11 on 2020-02-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pfm', '0003_auto_20200207_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleTambah',
        ),
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
