# Generated by Django 2.1.11 on 2020-02-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pfm', '0006_auto_20200207_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
